# Generated by Django 5.2.4 on 2025-09-12 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_document_file_alter_post_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='file',
        ),
        migrations.AddField(
            model_name='document',
            name='file_url',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
    ]
