# Generated by Django 5.2.4 on 2025-09-16 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_document_file_document_file_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
