# Generated by Django 5.2.4 on 2025-07-22 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_postimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='image',
        ),
        migrations.DeleteModel(
            name='PostImage',
        ),
    ]
